import assert from "node:assert/strict";import test from "node:test";import { calculateValuation,calculateWeightedAveragePosition,FINANCE_COST_METHOD } from "../src/lib/finance/calculations.ts";
import { associateFundTags, calculateMarketMood } from "../src/lib/finance/market-associations.ts";
test("cost strategy is weighted average",()=>assert.equal(FINANCE_COST_METHOD,"weighted_average"));
test("buy and sell preserve weighted average cost",()=>{const p=calculateWeightedAveragePosition([{type:"buy",shares:100,amount:1000,fee:10,occurredAt:"2026-01-01"},{type:"buy",shares:50,amount:600,fee:0,occurredAt:"2026-01-02"},{type:"sell",shares:30,amount:390,fee:3,occurredAt:"2026-01-03"}]);assert.deepEqual(p,{shares:120,costBasis:1288,averageCost:10.73333333,realizedPnl:65,cumulativeInvested:1223})});
test("valuation separates realized and unrealized pnl",()=>{const p=calculateWeightedAveragePosition([{type:"buy",shares:100,amount:1000,occurredAt:"2026-01-01"},{type:"sell",shares:20,amount:240,occurredAt:"2026-01-02"}]);assert.deepEqual(calculateValuation(p,13),{marketValue:1040,unrealizedPnl:240,totalReturn:280,returnRate:0.35})});
test("missing quote never creates fake valuation",()=>{const p=calculateWeightedAveragePosition([{type:"buy",shares:10,amount:100,occurredAt:"2026-01-01"}]);assert.deepEqual(calculateValuation(p,null),{marketValue:null,unrealizedPnl:null,totalReturn:null,returnRate:null})});
test("overselling is rejected",()=>assert.throws(()=>calculateWeightedAveragePosition([{type:"sell",shares:1,amount:10,occurredAt:"2026-01-01"}])));
test("market mood is calculated from real breadth",()=>{assert.equal(calculateMarketMood({advancing:3200,declining:1800,unchanged:100,dataTime:"2026-08-18"}),"strong");assert.equal(calculateMarketMood({advancing:1800,declining:3200,unchanged:100,dataTime:"2026-08-18"}),"weak");assert.equal(calculateMarketMood({advancing:2500,declining:2500,unchanged:100,dataTime:"2026-08-18"}),"sideways")});
test("fund tags only associate with matching real sectors",()=>{const result=associateFundTags(["科技","新能源"],[{name:"计算机服务",changePercent:1.2,dataTime:"2026-08-18"},{name:"光伏设备",changePercent:-1.1,dataTime:"2026-08-18"}]);assert.deepEqual(result.map(item=>[item.tag,item.direction]),[["科技","strong"],["新能源","weak"]])});
