import assert from "node:assert/strict";
import test from "node:test";
import { buildTrendFacts,hashFinanceAnalysisContext,type FinanceAnalysisContext } from "../src/lib/finance/analysis-context.ts";
import { assertFinanceAnalysisOutput } from "../src/lib/finance/analysis-output.ts";
import { buildFinanceAnalysisIdentity } from "../src/lib/finance/analysis-artifact-policy.ts";
import { buildOpenAIResponsesBody,parseOpenAIResponsesPayload } from "../src/lib/ai/openai-responses.ts";
import { buildDeepSeekChatBody,parseDeepSeekChatPayload } from "../src/lib/ai/deepseek-chat.ts";

function context():FinanceAnalysisContext{return {contextVersion:"finance-analysis-v1",marketFacts:{china:{indices:[{code:"000001",name:"上证指数",value:3700,changePercent:.5,marketTime:"2026-08-19T03:30:00.000Z"},{code:"000300",name:"沪深300",value:4100,changePercent:.4,marketTime:"2026-08-19T03:30:00.000Z"},{code:"000510",name:"中证A500",value:5200,changePercent:.3,marketTime:"2026-08-19T03:30:00.000Z"}],marketTime:"2026-08-19T03:30:00.000Z",fetchedAt:"2026-08-19T03:31:00.000Z",source:"市场参考行情"},us:{indices:[{code:"NDX",name:"NASDAQ-100",value:25000,changePercent:-.2,marketTime:"2026-08-18T20:00:00.000Z"},{code:"SPX",name:"S&P 500",value:6600,changePercent:.1,marketTime:"2026-08-18T20:00:00.000Z"},{code:"DJI",name:"Dow Jones",value:45000,changePercent:.05,marketTime:"2026-08-18T20:00:00.000Z"}],marketTime:"2026-08-18T20:00:00.000Z",fetchedAt:"2026-08-19T03:31:00.000Z",source:"市场参考行情"}},portfolioFacts:{marketValue:4000,invested:4300,profit:-300,profitRate:-300/4300},fundFacts:[{holdingId:"1",fundCode:"016453",fundName:"南方纳斯达克100指数发起(QDII)C",fundType:"指数型-海外股票",tags:[],shares:1000,invested:1100,latestNav:1,navDate:"2026-08-17",marketValue:1000,profit:-100,profitRate:-100/1100,isQdii:true}],contributionFacts:[{holdingId:"1",fundCode:"016453",fundName:"南方纳斯达克100指数发起(QDII)C",marketValue:1000,profit:-100,profitRate:-100/1100,assetShare:.25}],trendFacts:buildTrendFacts([{snapshot_date:"2026-08-19",total_market_value:4000,total_profit:-300}],"2026-08-19"),dataFreshness:{chinaMarketTime:"2026-08-19T03:30:00.000Z",usMarketTime:"2026-08-18T20:00:00.000Z",fundNavDates:[{fundCode:"016453",fundName:"南方纳斯达克100指数发起(QDII)C",navDate:"2026-08-17",isQdii:true}],snapshotStartDate:"2026-08-19",snapshotEndDate:"2026-08-19"},limitations:["组合目前只有 1 天真实 Snapshot"],unknownExposure:true};}

test("Context 保留六个真实指数、QDII 日期和一日历史限制",()=>{const value=context();assert.equal(value.marketFacts.china.indices.length,3);assert.equal(value.marketFacts.us.indices.length,3);assert.equal(value.fundFacts[0].navDate,"2026-08-17");assert.equal(value.trendFacts.snapshotDays,1);assert.equal(value.trendFacts.insufficientHistory,true);assert.equal(value.trendFacts.ranges.every(item=>item.insufficientHistory),true)});
test("Context Hash 稳定且事实变化后改变",()=>{const first=context(),same=context(),changed=context();changed.portfolioFacts.marketValue=4001;assert.equal(hashFinanceAnalysisContext(first),hashFinanceAnalysisContext(same));assert.notEqual(hashFinanceAnalysisContext(first),hashFinanceAnalysisContext(changed))});
test("两条真实 Snapshot 才产生确定性趋势差额",()=>{const result=buildTrendFacts([{snapshot_date:"2026-08-18",total_market_value:3900,total_profit:-400},{snapshot_date:"2026-08-19",total_market_value:4000,total_profit:-300}],"2026-08-19");assert.equal(result.insufficientHistory,false);assert.equal(result.ranges[0].marketValueChange,100);assert.equal(result.ranges[0].profitChange,100)});
test("Finance Artifact Schema 校验五部分完整报告",()=>{const output={summary:"组合仍处于亏损",marketReview:"A股温和上涨",holdingRelationship:"已知事实与可能影响分开说明",portfolioReview:"亏损主要来自当前基金",watchNext:["观察正式净值","观察指数","积累快照"],risks:["净值滞后"],dataLimitations:["历史不足"],dataAsOf:"2026-08-19"};assert.doesNotThrow(()=>assertFinanceAnalysisOutput(output));assert.throws(()=>assertFinanceAnalysisOutput({...output,watchNext:["只有一条"]}));assert.throws(()=>assertFinanceAnalysisOutput({...output,holdingRelationship:undefined}));assert.throws(()=>assertFinanceAnalysisOutput({...output,unknown:"no"}))});
test("同日同 Context 复用，不同自然日生成独立身份",()=>{const sameA=buildFinanceAnalysisIdentity("2026-08-20","abc"),sameB=buildFinanceAnalysisIdentity("2026-08-20","abc"),changed=buildFinanceAnalysisIdentity("2026-08-20","def"),tomorrow=buildFinanceAnalysisIdentity("2026-08-21","abc");assert.deepEqual(sameA,sameB);assert.equal(sameA.title,changed.title);assert.notEqual(sameA.deduplicationKey,changed.deduplicationKey);assert.notEqual(sameA.title,tomorrow.title);assert.notEqual(sameA.deduplicationKey,tomorrow.deduplicationKey)});
test("OpenAI Responses 使用严格 JSON Schema 并解析 token usage",()=>{const schema={type:"object",additionalProperties:false,properties:{summary:{type:"string"}},required:["summary"]};const body=buildOpenAIResponsesBody({model:"gpt-5.6-luna",system:"system",prompt:"facts",schemaName:"finance_analysis",schema,maxOutputTokens:1200});assert.deepEqual(body.text.format,{type:"json_schema",name:"finance_analysis",schema,strict:true});assert.equal(body.store,false);const parsed=parseOpenAIResponsesPayload({model:"gpt-5.6-luna",output:[{type:"message",content:[{type:"output_text",text:'{"summary":"ok"}'}]}],usage:{input_tokens:2400,output_tokens:600,total_tokens:3000}});assert.deepEqual(parsed.data,{summary:"ok"});assert.deepEqual(parsed.usage,{inputTokens:2400,outputTokens:600,totalTokens:3000})});
test("DeepSeek 使用官方 JSON Output、非思考模式并解析 token usage",()=>{const schema={type:"object",additionalProperties:false,properties:{summary:{type:"string"}},required:["summary"]};const body=buildDeepSeekChatBody({model:"deepseek-v4-flash",system:"system",prompt:"facts",schema,maxOutputTokens:1200,temperature:.2});assert.deepEqual(body.response_format,{type:"json_object"});assert.deepEqual(body.thinking,{type:"disabled"});assert.equal(body.messages[0].content.includes(JSON.stringify(schema)),true);const parsed=parseDeepSeekChatPayload({model:"deepseek-v4-flash",choices:[{finish_reason:"stop",message:{content:'{"summary":"ok"}'}}],usage:{prompt_tokens:2600,completion_tokens:700,total_tokens:3300}});assert.deepEqual(parsed.data,{summary:"ok"});assert.deepEqual(parsed.usage,{inputTokens:2600,outputTokens:700,totalTokens:3300});assert.throws(()=>parseDeepSeekChatPayload({choices:[{finish_reason:"length",message:{content:'{"summary":"cut"}'}}]}));assert.throws(()=>parseDeepSeekChatPayload({choices:[{finish_reason:"stop",message:{content:""}}]}))});
test("Market Research DeepSeek 请求使用独立的 4000 token 输出预算",()=>{const body=buildDeepSeekChatBody({model:"deepseek-v4-flash",system:"system",prompt:"facts",schema:{type:"object"},maxOutputTokens:4000,temperature:.2});assert.equal(body.max_tokens,4000)});
