import test from "node:test";
import assert from "node:assert/strict";
import {assertMarketResearchOutput,hashMarketResearchContext,validateMarketDailyBrief,type MarketDailyBriefDraft,type MarketResearchContext} from "../src/lib/finance/market-research.ts";

const context:MarketResearchContext={contextVersion:"market-research-v1",researchDate:"2026-08-24",marketOverview:{china:[],us:[]},marketStructure:{breadth:{advancers:3100,decliners:1800,unchanged:100,method:{sampleSize:5000,universe:"A股样本",filterRule:"排除停牌",sourceTimestamp:"2026-08-24T07:00:00Z",fetchedAt:"2026-08-24T07:01:00Z"}},limits:null,turnover:{amountCny:1.892e12,previousAmountCny:null,changePercent:null,method:{sampleSize:5000,universe:"A股样本",filterRule:"排除停牌",sourceTimestamp:"2026-08-24T07:00:00Z",fetchedAt:"2026-08-24T07:01:00Z"}},industries:{top:[],bottom:[],method:null},style:[]},macroEvents:[],marketNews:[{factId:"news-1",headline:"官方发布政策说明",sourceId:"source-1",publishedAt:"2026-08-24T01:00:00Z",factualSummary:"官方发布政策说明",relatedMarkets:["china"],confidence:"official"}],myFundExposure:[{factId:"fund-1",fundCode:"000001",fundName:"测试基金",relationshipStatus:"unknown",relationship:"暂无可靠暴露",navDate:"2026-08-22",sourceId:"source-1"}],facts:[{factId:"index-1",kind:"index",statement:"沪深300涨跌幅为-0.09%",value:-0.09,unit:"percent",sourceId:"source-1",sourceTimestamp:"2026-08-24T07:00:00Z"},{factId:"turnover-1",kind:"turnover",statement:"成交额为18920亿元",value:1.892e12,unit:"CNY",sourceId:"source-1",sourceTimestamp:"2026-08-24T07:00:00Z"},{factId:"fund-1",kind:"fund",statement:"测试基金NAV为1.234，正式净值日期为2026-08-22",value:1.234,unit:"nav",sourceId:"source-1",sourceTimestamp:"2026-08-22T00:00:00Z"},{factId:"news-1",kind:"news",statement:"官方发布政策说明",sourceId:"source-1",sourceTimestamp:"2026-08-24T01:00:00Z"}],sources:[{sourceId:"source-1",name:"测试官方来源",url:"https://example.com",level:"official",publishedAt:"2026-08-24T01:00:00Z",fetchedAt:"2026-08-24T07:01:00Z"}],dataLimitations:[],dataAsOf:{china:"2026-08-24T07:00:00Z",us:null,news:"2026-08-24T01:00:00Z",fetchedAt:"2026-08-24T07:01:00Z"}};
const prose="市场呈现分化格局，核心宽基的方向并不完全一致，情绪变化值得继续观察。现有事实支持对强弱结构进行解释，但不足以确认单一事件构成主要驱动。".repeat(7);
const valid:MarketDailyBriefDraft={schemaVersion:"market-daily-brief-v2",todayInOneSentence:{text:"市场分化，风险偏好仍需观察。",evidenceFactIds:["index-1"],sourceIds:["source-1"]},chinaMarket:{text:prose,evidenceFactIds:["index-1","turnover-1"],sourceIds:["source-1"]},overseasAndMacro:{text:prose,evidenceFactIds:["news-1"],sourceIds:["source-1"]},fundRelationship:{text:"当前只能确认正式净值日期，基金具体暴露仍未知。",evidenceFactIds:["fund-1"],sourceIds:["source-1"],relationshipStatus:"unknown"},drivers:{verifiedFacts:[{factId:"index-1",statement:"沪深300涨跌幅为-0.09%"}],possibleDrivers:[{text:"政策信息可能构成观察因素。",evidenceFactIds:["news-1"],relationship:"possible_influence",confidence:"low"}],unknowns:["当前事实不足以确认主要驱动因素"]},interpretations:[{text:"宽基表现分化，市场风险偏好仍需观察。",evidenceFactIds:["index-1"],relationship:"direction_aligned",confidence:"medium"}],watchNext:["宽基结构","成交变化","基金净值"].map((item,index)=>({item,whyItMatters:"与当前市场和持仓相关。",changesViewWhen:"相关事实出现明显变化。",evidenceFactIds:[index===2?"fund-1":"index-1"]})),unknowns:["基金实际行业暴露未知"],dataLimitations:[],dataAsOf:{chinaMarketTime:"2026-08-24T07:00:00Z",usMarketTime:null,newsTime:"2026-08-24T01:00:00Z"}};

test("v2 classifies fully grounded output as valid",()=>{const result=validateMarketDailyBrief(valid,context);assert.equal(result.validation.status,"valid");assert.equal(result.validation.hiddenClaims.length,0);});
test("schema/JSON structure failure is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,schemaVersion:"v1"} as never,context),/Schema 无效/));
test("nonexistent Fact ID is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,todayInOneSentence:{...valid.todayInOneSentence,evidenceFactIds:["missing"]}},context),/不存在的 Fact ID/));
test("nonexistent Source ID is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,chinaMarket:{...valid.chinaMarket,sourceIds:["missing"]}},context),/不存在的 Source ID/));
test("rewriting a verified news or market fact is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,drivers:{...valid.drivers,verifiedFacts:[{factId:"index-1",statement:"沪深300大幅上涨"}]}},context),/修改了已验证事实/));
test("fund exposure cannot be upgraded from unknown",()=>assert.throws(()=>validateMarketDailyBrief({...valid,fundRelationship:{...valid.fundRelationship,relationshipStatus:"verified"}},context),/缺少可靠基金暴露/));
test("unsupported market number in narrative becomes partial instead of rejected",()=>{const result=validateMarketDailyBrief({...valid,chinaMarket:{...valid.chinaMarket,text:`${prose} 沪深300涨跌幅为+0.09%。`}},context);assert.equal(result.validation.status,"partial");assert.doesNotMatch(result.chinaMarket.text,/\+0\.09%/);assert.equal(context.facts.find(fact=>fact.factId==="index-1")?.value,-0.09);});
test("unsupported turnover in narrative is hidden with a warning",()=>{const result=validateMarketDailyBrief({...valid,chinaMarket:{...valid.chinaMarket,text:`${prose} 成交额为1.95万亿元。`}},context);assert.equal(result.validation.status,"partial");assert.match(result.validation.warnings.join(" "),/1\.95万亿元/);});
test("fabricated fund NAV in the fund relationship field is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,fundRelationship:{...valid.fundRelationship,text:"测试基金NAV为9.99。"}},context),/无法追溯的基金事实数字/));
test("registered core number with deterministic unit conversion passes",()=>assert.doesNotThrow(()=>validateMarketDailyBrief({...valid,chinaMarket:{...valid.chinaMarket,text:`${prose} 成交额为1.892万亿元。`}},context)));
test("BLS unemployment with percent unit supports narrative 4.1%",()=>{const macro={factId:"macro-bls-LNS14000000",kind:"macro" as const,statement:"美国失业率最新发布值 4.1%（2026 M07）",value:4.1,unit:"percent",sourceId:"bls-LNS14000000",sourceTimestamp:null};const blsContext={...context,macroEvents:[macro],facts:[...context.facts,macro],sources:[...context.sources,{sourceId:"bls-LNS14000000",name:"U.S. Bureau of Labor Statistics",url:"https://www.bls.gov/data/",level:"official" as const,publishedAt:null,fetchedAt:"2026-08-24T07:01:00Z"}]};const result=validateMarketDailyBrief({...valid,overseasAndMacro:{text:`${prose} 美国失业率最新发布值为4.1%。`,evidenceFactIds:[macro.factId],sourceIds:[macro.sourceId]}},blsContext);assert.notEqual(result.validation.status,"rejected");assert.match(result.overseasAndMacro.text,/4\.1%/);});
test("unregistered analytical number hides one interpretation and returns partial",()=>{const result=validateMarketDailyBrief({...valid,interpretations:[...valid.interpretations,{text:"两类资产的相对差值为7.77。",evidenceFactIds:["index-1"],relationship:"direction_aligned",confidence:"low"}]},context);assert.equal(result.validation.status,"partial");assert.equal(result.interpretations.length,1);assert.equal(result.validation.hiddenClaims.length,1);});
test("unsupported interpretation without evidence becomes warning instead of rejection",()=>{const result=validateMarketDailyBrief({...valid,interpretations:[...valid.interpretations,{text:"市场情绪可能变化。",evidenceFactIds:[],relationship:"possible_influence",confidence:"low"}]},context);assert.equal(result.validation.status,"partial");assert.equal(result.interpretations.length,1);});
test("unsupported watch item is hidden instead of rejecting the brief",()=>{const result=validateMarketDailyBrief({...valid,watchNext:[...valid.watchNext,{item:"未知观察项",whyItMatters:"没有证据",changesViewWhen:"待确认",evidenceFactIds:[]}]},context);assert.equal(result.validation.status,"partial");assert.equal(result.watchNext.length,3);});
test("a non-core derived number in narrative is removed without rejecting the brief",()=>{const result=validateMarketDailyBrief({...valid,chinaMarket:{...valid.chinaMarket,text:`${prose} 相对强弱差约7.77。`}},context);assert.equal(result.validation.status,"partial");assert.doesNotMatch(result.chinaMarket.text,/7\.77/);});
test("a saved partial artifact remains displayable after refresh",()=>{const result=validateMarketDailyBrief({...valid,interpretations:[...valid.interpretations,{text:"辅助差值为7.77。",evidenceFactIds:["index-1"],relationship:"direction_aligned",confidence:"low"}]},context);assert.doesNotThrow(()=>assertMarketResearchOutput(result,context));});
test("news shortage degrades to partial",()=>{const noNews={...context,marketNews:[],dataLimitations:["新闻暂不可用"]};const result=validateMarketDailyBrief(valid,noNews);assert.equal(result.validation.status,"partial");assert.match(result.validation.warnings.join(" "),/可信新闻不足/);});
test("unsupported driver relationship is rejected",()=>assert.throws(()=>validateMarketDailyBrief({...valid,drivers:{...valid.drivers,possibleDrivers:[{...valid.drivers.possibleDrivers[0],relationship:"caused_by" as never}]}},context),/不允许的驱动关系/));
test("context hash is stable",()=>assert.equal(hashMarketResearchContext(context),hashMarketResearchContext(structuredClone(context))));
