import test from "node:test";
import assert from "node:assert/strict";
import { assertMarketResearchOutput,hashMarketResearchContext,type MarketResearchContext } from "../src/lib/finance/market-research.ts";

const context:MarketResearchContext={contextVersion:"market-research-v1",researchDate:"2026-08-23",marketOverview:{china:[],us:[]},marketStructure:{breadth:null,limits:null,turnover:null,industries:{top:[],bottom:[],method:null},style:[]},macroEvents:[],marketNews:[],myFundExposure:[],facts:[{factId:"fact-1",kind:"index",statement:"沪深300上涨",sourceId:"source-1",sourceTimestamp:"2026-08-22T07:00:00Z"}],sources:[{sourceId:"source-1",name:"测试来源",url:null,level:"market_reference",publishedAt:null,fetchedAt:"2026-08-23T00:00:00Z"}],dataLimitations:[],dataAsOf:{china:null,us:null,news:null,fetchedAt:"2026-08-23T00:00:00Z"}};
const paragraph="基于可验证事实进行审慎解释，当前信息只支持方向性观察，不能确认因果关系，也不能据此预测未来涨跌。".repeat(8);const valid={summary:"市场分化",coreConclusions:["一","二","三"],marketPanorama:paragraph,drivers:{verifiedFacts:[{factId:"fact-1",statement:"沪深300上涨"}],possibleDrivers:[{interpretation:"方向上具有一致性，值得继续观察",evidenceFactIds:["fact-1"],relationship:"direction_aligned" as const,confidence:"medium" as const}],unknowns:[]},marketStructure:paragraph,crossMarket:paragraph,fundRelationship:paragraph,watchNext:[1,2,3].map(i=>({item:`观察${i}`,why:"相关",changesViewWhen:"事实变化",evidenceFactIds:["fact-1"]})),risks:[],dataLimitations:[],dataAsOf:"2026-08-23"};
test("Market Research accepts traceable fact ids",()=>assert.doesNotThrow(()=>assertMarketResearchOutput(valid,context)));
test("Market Research rejects nonexistent fact ids",()=>assert.throws(()=>assertMarketResearchOutput({...valid,drivers:{...valid.drivers,verifiedFacts:[{factId:"missing",statement:"不存在"}]}},context),/不存在的 Fact ID/));
test("Market Research rejects unsupported causal wording",()=>assert.throws(()=>assertMarketResearchOutput({...valid,marketPanorama:"某事件导致市场上涨"},context),/确定性因果/));
test("Market Research rejects unsupported driver relationship",()=>assert.throws(()=>assertMarketResearchOutput({...valid,drivers:{...valid.drivers,possibleDrivers:[{...valid.drivers.possibleDrivers[0],relationship:"caused_by" as never}]}},context),/不允许的驱动关系/));
test("Market Research rejects ungrounded numbers",()=>assert.throws(()=>assertMarketResearchOutput({...valid,marketPanorama:`${paragraph} 999.99%`},context),/不存在的数字/));
test("Market Research treats zero-padded factual numbers as equivalent",()=>assert.doesNotThrow(()=>assertMarketResearchOutput({...valid,marketPanorama:`${paragraph} 7`},{...context,facts:[{...context.facts[0],statement:`${context.facts[0].statement}，样本月份 M07`}] })));
test("Market Research rejects nonexistent source ids",()=>assert.throws(()=>assertMarketResearchOutput(valid,{...context,facts:[{...context.facts[0],sourceId:"missing-source"}] }),/不存在的 Source ID/));
test("Market Research hash is stable",()=>assert.equal(hashMarketResearchContext(context),hashMarketResearchContext(structuredClone(context))));
