import type { ViralAnalysis } from "@/lib/content/viral-analysis";

const hookLabels: Record<string, string> = { benefit_conflict: "利益冲突", counterintuitive: "反常识", loss_aversion: "损失厌恶", strong_result: "强结果", strong_question: "强问题", identity: "身份代入", curiosity_gap: "好奇缺口", aesthetic_contrast: "审美反差", opinion_conflict: "观点冲突", other: "其他" };
const patternLabels: Record<string, string> = { hook: "Hook 机制", conflict: "冲突方式", information_structure: "信息结构", pacing: "节奏", user_psychology: "用户心理" };

export function ViralAnalysisReport({ analysis, analysisId, createTopic }: { analysis: ViralAnalysis; analysisId: string; createTopic: (analysisId: string, adaptationId: string) => Promise<void> }) {
  return <div className="space-y-6">
    <section className="rounded-3xl bg-surface p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-700">基础判断</p><h2 className="mt-3 text-2xl font-semibold">{analysis.topic}</h2><p className="mt-2 text-sm text-muted-foreground">{analysis.contentType} · {analysis.targetAudience}</p><div className="mt-5 rounded-2xl bg-violet-50 p-4"><p className="text-xs font-semibold text-violet-700">{hookLabels[analysis.hook.type] ?? analysis.hook.type}</p><p className="mt-2 font-semibold">{analysis.hook.text}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{analysis.hook.whyItWorks}</p></div></section>
    <section className="rounded-3xl bg-surface p-5 sm:p-6"><h2 className="text-xl font-semibold">爆款机制</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[["核心冲突",analysis.coreConflict],["用户痛点",analysis.painPoint],["信息差",analysis.informationGap],["情绪机制",analysis.emotionalMechanism],["收藏动机",analysis.saveMotivation],["评论动机",analysis.commentMotivation],["分享动机",analysis.shareMotivation],["涨粉可能性",analysis.followPotential]].map(([label,value])=><div key={label} className="rounded-2xl bg-surface-muted p-4"><dt className="text-xs font-semibold text-muted-foreground">{label}</dt><dd className="mt-2 text-sm leading-6">{value}</dd></div>)}</dl><ol className="mt-5 space-y-2">{analysis.contentStructure.map((item,index)=><li key={`${index}-${item}`} className="flex gap-3 text-sm"><span className="text-violet-700">{index+1}</span><span>{item}</span></li>)}</ol></section>
    <section className="rounded-3xl bg-surface p-5 sm:p-6"><h2 className="text-xl font-semibold">可以借鉴的机制</h2><div className="mt-4 space-y-3">{analysis.reusablePatterns.map(pattern=><article key={pattern.id} className="rounded-2xl border border-border p-4"><p className="text-xs font-semibold text-violet-700">{patternLabels[pattern.category] ?? pattern.category}</p><h3 className="mt-2 font-semibold">{pattern.mechanism}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{pattern.whyItWorks}</p><p className="mt-3 text-sm"><span className="font-medium">可迁移：</span>{pattern.transferableElements.join("、")}</p><p className="mt-1 text-sm text-muted-foreground"><span className="font-medium">不可复制：</span>{pattern.nonTransferableElements.join("、")}</p></article>)}</div><div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">不要复制</p><p className="mt-2 leading-6">{analysis.avoidCopying.join("；")}</p></div></section>
    <section><h2 className="text-xl font-semibold">改造成我的内容</h2><p className="mt-2 text-sm text-muted-foreground">选择一个方向进入现有选题库，不会复制原素材正文。</p><div className="mt-4 space-y-4">{analysis.adaptations.map(item=><article key={item.id} className="rounded-3xl bg-surface p-5 sm:p-6"><p className="text-xs font-semibold text-primary">{item.contentPillar} · {item.suggestedFormat}</p><h3 className="mt-2 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.whyItFitsCreator}</p><div className="mt-4 rounded-2xl bg-surface-muted p-4"><p className="text-xs font-semibold text-muted-foreground">推荐 Hook</p><p className="mt-2 font-medium">{item.hook}</p></div><p className="mt-4 text-sm"><span className="font-medium">角度：</span>{item.angle}</p><ol className="mt-3 space-y-1 text-sm text-muted-foreground">{item.structure.map((step,index)=><li key={`${index}-${step}`}>{index+1}. {step}</li>)}</ol><form action={createTopic.bind(null,analysisId,item.id)} className="mt-5"><button className="min-h-12 w-full rounded-2xl bg-primary px-4 font-semibold text-white">加入选题库</button></form></article>)}</div></section>
    {analysis.dataLimitations.length?<details className="rounded-2xl bg-surface-muted p-4 text-sm text-muted-foreground"><summary className="cursor-pointer font-medium text-foreground">数据说明</summary><ul className="mt-3 list-disc space-y-1 pl-5">{analysis.dataLimitations.map(item=><li key={item}>{item}</li>)}</ul></details>:null}
  </div>;
}
