"use server";import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { requireUser } from "@/server/auth/current-user";import { createDataAccess } from "@/server/data";
import { getFundNavProvider } from "@/server/funds";
async function ctx(){return{user:await requireUser(),data:await createDataAccess()}}function refresh(){revalidatePath("/finance","layout");revalidatePath("/dashboard")}
export async function saveAccountAction(id:string|null,form:FormData){const{user,data}=await ctx();await data.finance.accounts.save(user.id,id,form);refresh();redirect("/finance/accounts")}
export async function deleteAccountAction(id:string){const{user,data}=await ctx();await data.finance.accounts.remove(user.id,id);refresh()}
export async function saveInstrumentAction(id:string|null,form:FormData){const{user,data}=await ctx();await data.finance.instruments.save(user.id,id,form);refresh();redirect("/finance/instruments")}
export async function saveTransactionAction(form:FormData){const{user,data}=await ctx();const local=String(form.get("occurredAt")??"");if(local&&!/[zZ]|[+-]\d\d:\d\d$/.test(local))form.set("occurredAt",`${local}:00+08:00`);await data.finance.transactions.save(user.id,form);refresh();redirect("/finance/transactions")}
export async function deleteTransactionAction(id:string){const{user,data}=await ctx();await data.finance.transactions.remove(user.id,id);refresh()}
export async function saveFundAction(id:string|null,form:FormData){const{user,data}=await ctx();const savedId=await data.funds.save(user.id,id,form);let status="current";try{const provider=getFundNavProvider();const nav=await provider.getFormalNav(String(form.get("fundCode")??""));await data.funds.applyNav(user.id,savedId,nav);status="updated"}catch{const fund=await data.funds.get(user.id,savedId);status=fund.latest_nav!=null?"cached":"unavailable"}await data.fundTrends.upsertToday(user.id);refresh();redirect(`/finance/funds/${savedId}?refresh=${status}`)}
export async function deleteFundAction(id:string){const{user,data}=await ctx();await data.funds.remove(user.id,id);await data.fundTrends.upsertToday(user.id);refresh();redirect("/finance")}
export async function refreshFundAction(id:string){const{user,data}=await ctx();const fund=await data.funds.get(user.id,id);let status="unavailable",changed=false;try{const nav=await getFundNavProvider().getFormalNav(fund.fund_code);await data.funds.applyNav(user.id,id,nav);status=fund.nav_date===nav.latest.date?"current":"updated";changed=true}catch{status=fund.latest_nav!=null?"cached":"unavailable"}if(changed)await data.fundTrends.upsertToday(user.id);refresh();redirect(`/finance/funds/${id}?refresh=${status}`)}
export async function refreshAllFundNavAction(){const{user,data}=await ctx();const funds=await data.funds.list(user.id);let updated=0,current=0,cached=0,unavailable=0;for(const fund of funds){try{const nav=await getFundNavProvider().getFormalNav(fund.fund_code);await data.funds.applyNav(user.id,fund.id,nav);if(fund.nav_date===nav.latest.date)current+=1;else updated+=1}catch{if(fund.latest_nav!=null)cached+=1;else unavailable+=1}}await data.fundTrends.upsertToday(user.id);refresh();const result=updated>0?"updated":unavailable>0?"unavailable":cached>0?"cached":"current";redirect(`/finance?refresh=${result}&updated=${updated}&current=${current}&cached=${cached}&unavailable=${unavailable}`)}
