"use server";import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { requireUser } from "@/server/auth/current-user";import { createDataAccess } from "@/server/data";
import { getMarketDataProvider } from "@/server/market";
async function ctx(){return{user:await requireUser(),data:await createDataAccess()}}function refresh(){revalidatePath("/finance","layout");revalidatePath("/dashboard")}
export async function saveAccountAction(id:string|null,form:FormData){const{user,data}=await ctx();await data.finance.accounts.save(user.id,id,form);refresh();redirect("/finance/accounts")}
export async function deleteAccountAction(id:string){const{user,data}=await ctx();await data.finance.accounts.remove(user.id,id);refresh()}
export async function saveInstrumentAction(id:string|null,form:FormData){const{user,data}=await ctx();await data.finance.instruments.save(user.id,id,form);refresh();redirect("/finance/instruments")}
export async function saveTransactionAction(form:FormData){const{user,data}=await ctx();const local=String(form.get("occurredAt")??"");if(local&&!/[zZ]|[+-]\d\d:\d\d$/.test(local))form.set("occurredAt",`${local}:00+08:00`);await data.finance.transactions.save(user.id,form);refresh();redirect("/finance/transactions")}
export async function deleteTransactionAction(id:string){const{user,data}=await ctx();await data.finance.transactions.remove(user.id,id);refresh()}
export async function saveFundAction(id:string|null,form:FormData){const{user,data}=await ctx();const savedId=await data.funds.save(user.id,id,form);try{const provider=getMarketDataProvider();if(provider){const nav=await provider.getFundNavHistory(String(form.get("fundCode")??""));await data.funds.applyNav(user.id,savedId,nav)}}catch{}refresh();redirect(`/finance/funds/${savedId}`)}
export async function deleteFundAction(id:string){const{user,data}=await ctx();await data.funds.remove(user.id,id);refresh();redirect("/finance")}
export async function refreshFundAction(id:string){const{user,data}=await ctx();const fund=await data.funds.get(user.id,id);const provider=getMarketDataProvider();if(!provider)redirect(`/finance/funds/${id}?error=provider`);try{const nav=await provider.getFundNavHistory(fund.fund_code);await data.funds.applyNav(user.id,id,nav);refresh();redirect(`/finance/funds/${id}?updated=1`)}catch{redirect(`/finance/funds/${id}?error=fetch`)}}
