export const ACTIVITY_MULTIPLIERS = { sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725, very_active: 1.9 } as const;
export const MET_VALUES = { strength: 6, running: 8.3, walking: 3.5, cycling: 7.5, swimming: 6, yoga: 2.5 } as const;
export type ActivityLevel = keyof typeof ACTIVITY_MULTIPLIERS;
export type BiologicalSex = "female" | "male";

const finitePositive = (value: number | null | undefined) => typeof value === "number" && Number.isFinite(value) && value > 0;
export function calculateBmi(weightKg?: number | null, heightCm?: number | null) { if (!finitePositive(weightKg) || !finitePositive(heightCm)) return null; return Number((weightKg! / ((heightCm! / 100) ** 2)).toFixed(1)); }
export function calculateBmr(input: { weightKg?: number | null; heightCm?: number | null; age?: number | null; sex?: BiologicalSex | null }) { const { weightKg, heightCm, age, sex } = input; if (!finitePositive(weightKg) || !finitePositive(heightCm) || !finitePositive(age) || !sex) return null; const base = 10 * weightKg! + 6.25 * heightCm! - 5 * age!; return Math.round(base + (sex === "male" ? 5 : -161)); }
export function calculateTdee(bmr?: number | null, activity: ActivityLevel = "sedentary", exerciseKcal = 0) { if (!finitePositive(bmr) || !Number.isFinite(exerciseKcal) || exerciseKcal < 0) return null; return Math.round(bmr! * ACTIVITY_MULTIPLIERS[activity] + exerciseKcal); }
export function calculateMetCalories(input: { met?: number | null; weightKg?: number | null; durationMinutes?: number | null }) { const { met, weightKg, durationMinutes } = input; if (!finitePositive(met) || !finitePositive(weightKg) || !finitePositive(durationMinutes)) return null; return Math.round((met! * 3.5 * weightKg! / 200) * durationMinutes!); }
export type NutritionTotal={caloriesKcal:number;proteinG:number;carbsG:number;fatG:number};
export function calculateNutrition(items: Array<{ caloriesKcal?: number | null; proteinG?: number | null; carbsG?: number | null; fatG?: number | null }>):NutritionTotal { return items.reduce<NutritionTotal>((sum, item) => ({ caloriesKcal: sum.caloriesKcal + Number(item.caloriesKcal ?? 0), proteinG: sum.proteinG + Number(item.proteinG ?? 0), carbsG: sum.carbsG + Number(item.carbsG ?? 0), fatG: sum.fatG + Number(item.fatG ?? 0) }), { caloriesKcal: 0, proteinG: 0, carbsG: 0, fatG: 0 }); }
export function calculateCalorieBalance(intake?: number | null, estimatedBurn?: number | null) { if (intake == null || estimatedBurn == null || !Number.isFinite(intake) || !Number.isFinite(estimatedBurn)) return null; return Math.round(intake - estimatedBurn); }
const dayMs = 86_400_000;
export function calculateCycleStats(startDates: string[]) { const dates = [...new Set(startDates)].map((date) => new Date(`${date}T00:00:00Z`)).filter((date) => !Number.isNaN(date.valueOf())).sort((a, b) => a.valueOf() - b.valueOf()); const lengths = dates.slice(1).map((date, index) => Math.round((date.valueOf() - dates[index].valueOf()) / dayMs)).filter((days) => days > 0); if (!lengths.length) return { lengths: [], latestLength: null, averageLength: null, nextExpectedDate: null, highlyVariable: false }; const averageLength = Math.round(lengths.reduce((sum, value) => sum + value, 0) / lengths.length); const next = new Date(dates.at(-1)!.valueOf() + averageLength * dayMs); return { lengths, latestLength: lengths.at(-1)!, averageLength, nextExpectedDate: next.toISOString().slice(0, 10), highlyVariable: Math.max(...lengths) - Math.min(...lengths) > 7 }; }
export function calorieBalanceLabel(balance: number | null) { if (balance == null) return "暂无估算"; if (balance < -100) return "热量缺口"; if (balance > 100) return "热量盈余"; return "热量平衡"; }
