import "server-only";
import { createClient } from "@/lib/supabase/server";
import { getDayBounds,getLocalDate } from "@/lib/date";
import { createDataAccess } from "@/server/data";
import { getProvider } from "./registry";
import { TASK_CONFIG } from "./config";
import { briefSchema,reviewSchema,viralSchema } from "./schemas";
import { AiProviderFailure,type AiTaskType,type StructuredResult } from "./types";

type Source={title:string;url?:string|null;type:string;dataAsOf?:string|null};
type RunInput={userId:string;task:AiTaskType;title:string;artifactType:string;artifactMode?:"append"|"daily_latest";schema:Record<string,unknown>;context:unknown;sources:Source[];deduplicationKey?:string;inputHash?:string;dataAsOf?:string;validateOutput?:(value:Record<string,unknown>)=>void;processOutput?:(value:Record<string,unknown>)=>Record<string,unknown>};
const systems:Record<AiTaskType,string>={daily_brief:"你是 Kiki Personal OS 的每日规划分析器。只根据给定数据生成中文结构化报告，不创建或修改任务。事实、推断、建议必须严格分开；数据不足要明确说明。",evening_summary:"你是 Kiki Personal OS 的晚间整理器。只根据当日事实和用户复盘总结。事实、用户判断、AI推断和明日建议必须分开。记忆只能作为待确认提议，不能自动激活。",viral_material_analysis:"你是严谨的自媒体内容分析师。只分析输入素材与用户画像，不假装看过链接内容。区分事实、AI推断、建议；数据不足要明确说明。",content_review:"你是审慎的内容复盘分析师。不能根据单一指标给确定性结论。结合最新指标、选题来源和用户笔记，区分事实、推断和建议。",finance_analysis:"你是 Kiki Personal OS 的个人财富解释器。只能解释输入的确定性事实，不能修改或重算金额、份额、成本、净值、收益、贡献、快照或指数涨跌。不得编造新闻、行情、基金权重、行业暴露、国家比例或个股持仓；只可使用明确提供的基金类型与标签。holdingRelationship 必须区分已知事实与可能影响，严禁把指数涨跌直接等同于基金净值或用户收益。QDII 必须引用正式 NAV 日期并说明时间滞后。Snapshot 历史不足时必须明确不能判断趋势，不得倒推、补点或插值。不得预测确定涨跌，不得输出买入、卖出、加仓、减仓或仓位比例指令。",market_research:"你是用户的个人每日财经市场解读助手，不是数据复读器，也不是合规报告生成器。严格输出 Market Daily Brief v2 JSON，正文约 1500～2500 个中文字符。先判断今天市场整体强弱，再寻找真正值得注意的结构：市场宽度、大盘与小盘相对表现、行业或板块分化、成交活跃度、风险偏好变化、A股与海外是否同向，以及宏观事件与市场表现可能存在的联系。允许并鼓励概率性市场判断，可使用‘更像是’‘市场呈现’‘资金可能更偏向’‘从市场结构看’‘值得注意的是’‘这通常意味着’‘一个可能的解释是’等自然表达。不要把推测写成已证实事实，也不要编造 Context 中不存在的事件。正文不要在每个判断后反复声明‘缺乏直接证据’‘无法确认’‘数据不足’；将限制统一放入 unknowns 或 dataLimitations。核心数字由页面从 Context 渲染，不要机械重复指数点位、成交额、市场宽度、基金金额或 NAV。todayInOneSentence 应用一句有主次的话说清今日市场；chinaMarket 解释 A 股强弱和结构；overseasAndMacro 只提炼真正值得注意的海外与宏观变化；fundRelationship 只建立能够可靠确认的基金关系。interpretations 与 drivers.possibleDrivers 用于回答‘今天市场在交易什么’，每项都要有 evidenceFactIds，要有观点而不是重复数据；relationship 仅允许 time_aligned、direction_aligned、possible_influence。watchNext 优先输出下一交易日最值得盯的 3 件事，按当日核心结构、行业或风格变化、成交/宽度/重要宏观事件排序；每项用一个标题和一段简洁说明。证据不足时不要凑数，限制放入 unknowns/dataLimitations。所有引用必须来自真实 evidenceFactIds/sourceIds；不得编造新闻、政策、事件、来源、行情、正式宏观数据、基金净值、收益、权重或资产暴露；relationshipStatus=unknown 时不得根据基金名称猜测；不得把指数涨跌写成基金实际收益。非必要不要自行生成新数字。不得输出确定性涨跌预测，不得给出买入、卖出、加仓、减仓或具体仓位比例指令。"};

export async function execute(input:RunInput){
  const client=await createClient(); const provider=getProvider(input.task); const cfg=TASK_CONFIG[input.task];
  const existing=input.deduplicationKey?await client.from("ai_jobs").select("id,status,attempt_count").eq("user_id",input.userId).eq("deduplication_key",input.deduplicationKey).maybeSingle<{id:string;status:string;attempt_count:number}>():{data:null,error:null};
  if(existing.error)throw new Error(existing.error.message);
  if(existing.data?.status==="ready"){
    const {data:readyRun,error}=await client.from("ai_runs").select("artifact_id").eq("user_id",input.userId).eq("job_id",existing.data.id).eq("status","ready").not("artifact_id","is",null).order("completed_at",{ascending:false}).limit(1).maybeSingle<{artifact_id:string}>();if(error)throw new Error(error.message);
    if(readyRun?.artifact_id){const {data:artifact,error:artifactError}=await client.from("ai_artifacts").select("id,version,content").eq("user_id",input.userId).eq("id",readyRun.artifact_id).single<{id:string;version:number;content:Record<string,unknown>}>();if(artifactError||!artifact)throw new Error(artifactError?.message??"已生成报告读取失败");return{artifactId:artifact.id,version:artifact.version,data:artifact.content,reused:true};}
  }
  if(existing.data?.status==="running")throw new Error("相同数据的分析正在生成，请稍候");
  let job:{id:string};
  if(existing.data){const {data,error}=await client.from("ai_jobs").update({status:"running",attempt_count:Number(existing.data.attempt_count??0)+1}).eq("user_id",input.userId).eq("id",existing.data.id).select("id").single<{id:string}>();if(error||!data)throw new Error(error?.message??"AI Job 更新失败");job=data;}
  else {const {data,error}=await client.from("ai_jobs").insert({user_id:input.userId,agent_type:input.task,trigger_type:"user",status:"running",input_refs:{sources:input.sources.map(x=>({title:x.title,type:x.type}))},attempt_count:1,deduplication_key:input.deduplicationKey??null}).select("id").single<{id:string}>();if(error||!data)throw new Error(error?.message??"AI Job 创建失败");job=data;}
  const {data:run,error:runError}=await client.from("ai_runs").insert({user_id:input.userId,job_id:job.id,agent_type:input.task,provider:provider.id,model:provider.model,prompt_version:input.task==="market_research"?"market-daily-brief-v2":input.task==="finance_analysis"?"finance-v1":"phase3-v1",output_schema_version:input.task==="market_research"?"2":"1",status:"running",input_hash:input.inputHash??null}).select("id").single<{id:string}>(); if(runError||!run) throw new Error(runError?.message??"AI Run 创建失败");
  const runStarted=Date.now();
  let providerResult:StructuredResult|undefined;
  try{
    const serialized=JSON.stringify(input.context).slice(0,cfg.maxInputChars);
    const result=await provider.generateStructured({taskType:input.task,system:systems[input.task],input:serialized,schemaName:input.task,schema:input.schema,timeoutMs:cfg.timeoutMs,maxOutputTokens:cfg.maxOutputTokens,temperature:cfg.temperature,reasoning:cfg.reasoning});providerResult=result;
    const output=input.processOutput?input.processOutput(result.data):result.data;
    input.validateOutput?.(output);
    const {data:latest}=await client.from("ai_artifacts").select("version").eq("user_id",input.userId).eq("artifact_type",input.artifactType).order("version",{ascending:false}).limit(1).maybeSingle<{version:number}>();
    const {data:dailyArtifact,error:dailyError}=input.artifactMode==="daily_latest"?await client.from("ai_artifacts").select("id,version").eq("user_id",input.userId).eq("artifact_type",input.artifactType).eq("title",input.title).order("generated_at",{ascending:false}).limit(1).maybeSingle<{id:string;version:number}>():{data:null,error:null};if(dailyError)throw new Error(dailyError.message);
    const summary=String(output.summary??((output.todayInOneSentence as Record<string,unknown>|undefined)?.text)??output.overall_judgment??output.core_reason??((output.today_focus as string[]|undefined)?.[0])??"AI 分析报告").slice(0,500);
    const dataAsOf=input.dataAsOf??new Date().toISOString();
    const artifactRow={run_id:run.id,artifact_type:input.artifactType,title:input.title,summary,content:output,version:(latest?.version??0)+1,data_as_of:dataAsOf,generated_at:new Date().toISOString()};
    const artifactResult=dailyArtifact?await client.from("ai_artifacts").update(artifactRow).eq("user_id",input.userId).eq("id",dailyArtifact.id).select("id,version").single<{id:string;version:number}>():await client.from("ai_artifacts").insert({user_id:input.userId,...artifactRow}).select("id,version").single<{id:string;version:number}>();const artifact=artifactResult.data,artifactError=artifactResult.error;if(artifactError||!artifact)throw new Error(artifactError?.message??"Artifact 保存失败");
    if(dailyArtifact){const {error}=await client.from("ai_artifact_sources").delete().eq("user_id",input.userId).eq("artifact_id",artifact.id);if(error)throw new Error(error.message);}
    if(input.sources.length){const {error}=await client.from("ai_artifact_sources").insert(input.sources.map((source,index)=>({artifact_id:artifact.id,user_id:input.userId,source_title:source.title,source_url:source.url??null,source_type:source.type,citation_order:index,data_as_of:source.dataAsOf??dataAsOf}))); if(error) throw new Error(error.message);}
    await client.from("ai_runs").update({status:"ready",provider:result.provider,model:result.model,input_tokens:result.usage.inputTokens,output_tokens:result.usage.outputTokens,total_tokens:result.usage.totalTokens,latency_ms:result.latencyMs,artifact_id:artifact.id,completed_at:new Date().toISOString()}).eq("user_id",input.userId).eq("id",run.id);
    await client.from("ai_jobs").update({status:"ready"}).eq("user_id",input.userId).eq("id",job.id);
    return {artifactId:artifact.id,version:artifact.version,data:output,reused:false};
  }catch(error){const message=error instanceof Error?error.message:"未知 Provider 错误",failureResult=error instanceof AiProviderFailure?error.metadata:providerResult;await client.from("ai_runs").update({status:"failed",error_code:message.includes("超时")?"timeout":"provider_error",error_message:message.slice(0,1000),provider:failureResult?.provider??provider.id,model:failureResult?.model??provider.model,input_tokens:failureResult?.usage.inputTokens??null,output_tokens:failureResult?.usage.outputTokens??null,total_tokens:failureResult?.usage.totalTokens??null,latency_ms:failureResult?.latencyMs??Date.now()-runStarted,completed_at:new Date().toISOString()}).eq("user_id",input.userId).eq("id",run.id);await client.from("ai_jobs").update({status:"failed"}).eq("user_id",input.userId).eq("id",job.id);throw error;}
}

export async function analyzeViralMaterial(userId:string,materialId:string){const data=await createDataAccess();const [material,profile]=await Promise.all([data.content.materials.get(userId,materialId),data.profiles.get(userId)]);if(!material)throw new Error("素材不存在");const result=await execute({userId,task:"viral_material_analysis",title:`爆款拆解：${material.title}`,artifactType:`viral_material_analysis:${material.id}`,schema:viralSchema,context:{material:{title:material.title,platform:material.platform,author:material.author_name,metrics:{views:material.views,likes:material.likes,comments:material.comments,saves:material.saves,shares:material.shares},tags:material.tags,notes:material.notes,source_url:material.source_url},profile:{content_positioning:profile?.content_positioning,target_audience:profile?.target_audience,response_style:profile?.ai_response_style}},sources:[{title:material.title,url:material.source_url,type:"viral_material"}]});const client=await createClient();const {data:artifact}=await client.from("ai_artifacts").select("id,version").eq("id",result.artifactId).single<{id:string;version:number}>();await client.from("media_material_analyses").insert({user_id:userId,material_id:material.id,analysis_type:"video_breakdown",version:artifact?.version??result.version,result:result.data,ai_artifact_id:result.artifactId});return result;}

export async function analyzeContentReview(userId:string,publicationId:string){const data=await createDataAccess();const publication=await data.content.publications.get(userId,publicationId);if(!publication)throw new Error("发布记录不存在");const [metrics,review,topic]=await Promise.all([data.content.publications.metrics(userId,publicationId),data.content.reviews.getByPublication(userId,publicationId),publication.topic_id?data.content.topics.get(userId,publication.topic_id):null]);const sources=topic?await data.content.topics.sources(userId,topic.id):[];const result=await execute({userId,task:"content_review",title:`内容复盘：${publication.title}`,artifactType:`content_review:${publication.id}`,schema:reviewSchema,context:{publication,latest_metric:metrics[0]??null,topic,topic_sources:sources,user_review:review??null},sources:[{title:publication.title,url:publication.content_url,type:"publication"},{title:topic?.title??"原选题",url:topic?.reference_url,type:"topic"}]});const client=await createClient();if(review)await client.from("media_content_reviews").update({ai_artifact_id:result.artifactId}).eq("user_id",userId).eq("id",review.id);return result;}

export async function generateDailyBrief(userId:string){const data=await createDataAccess();const profile=await data.profiles.get(userId);const date=getLocalDate(profile?.timezone);const bounds=getDayBounds(date);const sevenDaysAgo=new Date(bounds.start);sevenDaysAgo.setDate(sevenDaysAgo.getDate()-7);const client=await createClient();const [todayTasks,daily,contentOverview,recentTasks,recentPubs,recentMetrics,memories]=await Promise.all([data.tasks.list(userId,date),data.daily.getOrCreate(userId,date),data.content.getOverview(userId),client.from("tasks").select("title,status,priority,scheduled_date").eq("user_id",userId).is("deleted_at",null).gte("created_at",sevenDaysAgo.toISOString()).limit(30),data.content.publications.list(userId),client.from("media_publication_metrics").select("recorded_at,views,likes,comments,shares,saves,followers_gained,completion_rate").eq("user_id",userId).gte("recorded_at",sevenDaysAgo.toISOString()).order("recorded_at",{ascending:false}).limit(10),client.from("memory_items").select("memory_type,domain,title,content,importance").eq("user_id",userId).eq("status","active").eq("ai_access","allowed").eq("sensitivity","normal").in("domain",["global","media","work"]).is("deleted_at",null).order("importance",{ascending:false}).limit(5)]);const focus=await data.daily.listFocus(userId,daily.id);return execute({userId,task:"daily_brief",title:`AI 每日简报 · ${date}`,artifactType:"daily_brief",schema:briefSchema,context:{date,profile_lite:{content_positioning:profile?.content_positioning,target_audience:profile?.target_audience,response_style:profile?.ai_response_style},today_tasks:todayTasks.slice(0,15),today_focus:focus.slice(0,5),recent_7_day_tasks:(recentTasks.data??[]).slice(0,30),recent_memory:(memories.data??[]).slice(0,5),content_summary:contentOverview,recent_publications:recentPubs.slice(0,5),recent_7_day_metrics:(recentMetrics.data??[]).slice(0,10)},sources:[{title:"今日任务与重点",type:"tasks"},{title:"最近 7 天任务摘要",type:"tasks"},{title:"最近自媒体数据摘要",type:"content"},{title:"允许 AI 访问的少量记忆",type:"memory"}]});}
