import "server-only";
import { createClient } from "@/lib/supabase/server";
import { getDayBounds,getLocalDate } from "@/lib/date";
import { createDataAccess } from "@/server/data";
import { getProvider } from "./registry";
import { TASK_CONFIG } from "./config";
import { briefSchema,reviewSchema,viralSchema } from "./schemas";
import type { AiTaskType } from "./types";

type Source={title:string;url?:string|null;type:string;dataAsOf?:string|null};
type RunInput={userId:string;task:AiTaskType;title:string;artifactType:string;schema:Record<string,unknown>;context:unknown;sources:Source[];deduplicationKey?:string;inputHash?:string;dataAsOf?:string;validateOutput?:(value:Record<string,unknown>)=>void};
const systems:Record<AiTaskType,string>={daily_brief:"你是 Kiki Personal OS 的每日规划分析器。只根据给定数据生成中文结构化报告，不创建或修改任务。事实、推断、建议必须严格分开；数据不足要明确说明。",evening_summary:"你是 Kiki Personal OS 的晚间整理器。只根据当日事实和用户复盘总结。事实、用户判断、AI推断和明日建议必须分开。记忆只能作为待确认提议，不能自动激活。",viral_material_analysis:"你是严谨的自媒体内容分析师。只分析输入素材与用户画像，不假装看过链接内容。区分事实、AI推断、建议；数据不足要明确说明。",content_review:"你是审慎的内容复盘分析师。不能根据单一指标给确定性结论。结合最新指标、选题来源和用户笔记，区分事实、推断和建议。",finance_analysis:"你是 Kiki Personal OS 的个人财富解释器。只能解释输入的确定性事实，不能重算金额、净值、收益、贡献或指数涨跌，不能搜索或编造新闻原因，不能猜测行业、国家、个股权重。QDII 必须引用其正式净值日期；历史不足时必须明确不能判断趋势。输出观察项而非买卖、仓位或收益保证。"};

export async function execute(input:RunInput){
  const client=await createClient(); const provider=getProvider(input.task); const cfg=TASK_CONFIG[input.task];
  const existing=input.deduplicationKey?await client.from("ai_jobs").select("id,status,attempt_count").eq("user_id",input.userId).eq("deduplication_key",input.deduplicationKey).maybeSingle<{id:string;status:string;attempt_count:number}>():{data:null,error:null};
  if(existing.error)throw new Error(existing.error.message);
  if(existing.data?.status==="ready"){
    const {data:readyRun,error}=await client.from("ai_runs").select("artifact_id").eq("user_id",input.userId).eq("job_id",existing.data.id).eq("status","ready").not("artifact_id","is",null).order("completed_at",{ascending:false}).limit(1).maybeSingle<{artifact_id:string}>();if(error)throw new Error(error.message);
    if(readyRun?.artifact_id){const {data:artifact,error:artifactError}=await client.from("ai_artifacts").select("id,version,content").eq("user_id",input.userId).eq("id",readyRun.artifact_id).single<{id:string;version:number;content:Record<string,unknown>}>();if(artifactError||!artifact)throw new Error(artifactError?.message??"已生成报告读取失败");return{artifactId:artifact.id,version:artifact.version,data:artifact.content,reused:true};}
  }
  if(existing.data?.status==="running")throw new Error("相同数据的分析正在生成，请稍候");
  let job:{id:string};
  if(existing.data){const {data,error}=await client.from("ai_jobs").update({status:"running",attempt_count:Number(existing.data.attempt_count??0)+1}).eq("user_id",input.userId).eq("id",existing.data.id).select("id").single<{id:string}>();if(error||!data)throw new Error(error?.message??"AI Job 更新失败");job=data;}
  else {const {data,error}=await client.from("ai_jobs").insert({user_id:input.userId,agent_type:input.task,trigger_type:"user",status:"running",input_refs:{sources:input.sources.map(x=>({title:x.title,type:x.type}))},attempt_count:1,deduplication_key:input.deduplicationKey??null}).select("id").single<{id:string}>();if(error||!data)throw new Error(error?.message??"AI Job 创建失败");job=data;}
  const {data:run,error:runError}=await client.from("ai_runs").insert({user_id:input.userId,job_id:job.id,agent_type:input.task,provider:provider.id,model:provider.model,prompt_version:input.task==="finance_analysis"?"finance-v1":"phase3-v1",output_schema_version:"1",status:"running",input_hash:input.inputHash??null}).select("id").single<{id:string}>(); if(runError||!run) throw new Error(runError?.message??"AI Run 创建失败");
  try{
    const serialized=JSON.stringify(input.context).slice(0,cfg.maxInputChars);
    const result=await provider.generateStructured({taskType:input.task,system:systems[input.task],input:serialized,schemaName:input.task,schema:input.schema,timeoutMs:cfg.timeoutMs,maxOutputTokens:cfg.maxOutputTokens,temperature:cfg.temperature,reasoning:cfg.reasoning});
    input.validateOutput?.(result.data);
    const {data:latest}=await client.from("ai_artifacts").select("version").eq("user_id",input.userId).eq("artifact_type",input.artifactType).order("version",{ascending:false}).limit(1).maybeSingle<{version:number}>();
    const summary=String(result.data.summary??result.data.overall_judgment??result.data.core_reason??((result.data.today_focus as string[]|undefined)?.[0])??"AI 分析报告").slice(0,500);
    const dataAsOf=input.dataAsOf??new Date().toISOString();
    const {data:artifact,error:artifactError}=await client.from("ai_artifacts").insert({user_id:input.userId,run_id:run.id,artifact_type:input.artifactType,title:input.title,summary,content:result.data,version:(latest?.version??0)+1,data_as_of:dataAsOf}).select("id,version").single<{id:string;version:number}>(); if(artifactError||!artifact) throw new Error(artifactError?.message??"Artifact 保存失败");
    if(input.sources.length){const {error}=await client.from("ai_artifact_sources").insert(input.sources.map((source,index)=>({artifact_id:artifact.id,user_id:input.userId,source_title:source.title,source_url:source.url??null,source_type:source.type,citation_order:index,data_as_of:source.dataAsOf??dataAsOf}))); if(error) throw new Error(error.message);}
    await client.from("ai_runs").update({status:"ready",input_tokens:result.usage.inputTokens,output_tokens:result.usage.outputTokens,total_tokens:result.usage.totalTokens,latency_ms:result.latencyMs,artifact_id:artifact.id,completed_at:new Date().toISOString()}).eq("user_id",input.userId).eq("id",run.id);
    await client.from("ai_jobs").update({status:"ready"}).eq("user_id",input.userId).eq("id",job.id);
    return {artifactId:artifact.id,version:artifact.version,data:result.data,reused:false};
  }catch(error){const message=error instanceof Error?error.message:"未知 Provider 错误";await client.from("ai_runs").update({status:"failed",error_code:"provider_error",error_message:message.slice(0,1000),completed_at:new Date().toISOString()}).eq("user_id",input.userId).eq("id",run.id);await client.from("ai_jobs").update({status:"failed"}).eq("user_id",input.userId).eq("id",job.id);throw error;}
}

export async function analyzeViralMaterial(userId:string,materialId:string){const data=await createDataAccess();const [material,profile]=await Promise.all([data.content.materials.get(userId,materialId),data.profiles.get(userId)]);if(!material)throw new Error("素材不存在");const result=await execute({userId,task:"viral_material_analysis",title:`爆款拆解：${material.title}`,artifactType:`viral_material_analysis:${material.id}`,schema:viralSchema,context:{material:{title:material.title,platform:material.platform,author:material.author_name,metrics:{views:material.views,likes:material.likes,comments:material.comments,saves:material.saves,shares:material.shares},tags:material.tags,notes:material.notes,source_url:material.source_url},profile:{content_positioning:profile?.content_positioning,target_audience:profile?.target_audience,response_style:profile?.ai_response_style}},sources:[{title:material.title,url:material.source_url,type:"viral_material"}]});const client=await createClient();const {data:artifact}=await client.from("ai_artifacts").select("id,version").eq("id",result.artifactId).single<{id:string;version:number}>();await client.from("media_material_analyses").insert({user_id:userId,material_id:material.id,analysis_type:"video_breakdown",version:artifact?.version??result.version,result:result.data,ai_artifact_id:result.artifactId});return result;}

export async function analyzeContentReview(userId:string,publicationId:string){const data=await createDataAccess();const publication=await data.content.publications.get(userId,publicationId);if(!publication)throw new Error("发布记录不存在");const [metrics,review,topic]=await Promise.all([data.content.publications.metrics(userId,publicationId),data.content.reviews.getByPublication(userId,publicationId),publication.topic_id?data.content.topics.get(userId,publication.topic_id):null]);const sources=topic?await data.content.topics.sources(userId,topic.id):[];const result=await execute({userId,task:"content_review",title:`内容复盘：${publication.title}`,artifactType:`content_review:${publication.id}`,schema:reviewSchema,context:{publication,latest_metric:metrics[0]??null,topic,topic_sources:sources,user_review:review??null},sources:[{title:publication.title,url:publication.content_url,type:"publication"},{title:topic?.title??"原选题",url:topic?.reference_url,type:"topic"}]});const client=await createClient();if(review)await client.from("media_content_reviews").update({ai_artifact_id:result.artifactId}).eq("user_id",userId).eq("id",review.id);return result;}

export async function generateDailyBrief(userId:string){const data=await createDataAccess();const profile=await data.profiles.get(userId);const date=getLocalDate(profile?.timezone);const bounds=getDayBounds(date);const sevenDaysAgo=new Date(bounds.start);sevenDaysAgo.setDate(sevenDaysAgo.getDate()-7);const client=await createClient();const [todayTasks,daily,contentOverview,recentTasks,recentPubs,recentMetrics,memories]=await Promise.all([data.tasks.list(userId,date),data.daily.getOrCreate(userId,date),data.content.getOverview(userId),client.from("tasks").select("title,status,priority,scheduled_date").eq("user_id",userId).is("deleted_at",null).gte("created_at",sevenDaysAgo.toISOString()).limit(30),data.content.publications.list(userId),client.from("media_publication_metrics").select("recorded_at,views,likes,comments,shares,saves,followers_gained,completion_rate").eq("user_id",userId).gte("recorded_at",sevenDaysAgo.toISOString()).order("recorded_at",{ascending:false}).limit(10),client.from("memory_items").select("memory_type,domain,title,content,importance").eq("user_id",userId).eq("status","active").eq("ai_access","allowed").eq("sensitivity","normal").in("domain",["global","media","work"]).is("deleted_at",null).order("importance",{ascending:false}).limit(5)]);const focus=await data.daily.listFocus(userId,daily.id);return execute({userId,task:"daily_brief",title:`AI 每日简报 · ${date}`,artifactType:"daily_brief",schema:briefSchema,context:{date,profile_lite:{content_positioning:profile?.content_positioning,target_audience:profile?.target_audience,response_style:profile?.ai_response_style},today_tasks:todayTasks.slice(0,15),today_focus:focus.slice(0,5),recent_7_day_tasks:(recentTasks.data??[]).slice(0,30),recent_memory:(memories.data??[]).slice(0,5),content_summary:contentOverview,recent_publications:recentPubs.slice(0,5),recent_7_day_metrics:(recentMetrics.data??[]).slice(0,10)},sources:[{title:"今日任务与重点",type:"tasks"},{title:"最近 7 天任务摘要",type:"tasks"},{title:"最近自媒体数据摘要",type:"content"},{title:"允许 AI 访问的少量记忆",type:"memory"}]});}
