import Link from "next/link";
import { LearningNav } from "@/components/learning/learning-nav";
import { requireUser } from "@/server/auth/current-user";
import { createDataAccess } from "@/server/data";
import { deleteNoteAction, favoriteNoteAction } from "../actions";

export default async function NotesPage({ searchParams }: { searchParams: Promise<{ q?: string; skillId?: string; favorite?: string }> }) {
  const filters = await searchParams; const user = await requireUser(); const data = await createDataAccess();
  const [allNotes, skills] = await Promise.all([data.learning.notes.list(user.id, filters.skillId, filters.q), data.learning.skills.list(user.id)]);
  const notes = filters.favorite === "1" ? allNotes.filter((note) => note.is_favorite) : allNotes; const skillNames = new Map(skills.map((skill) => [skill.id, skill.name]));
  return <main className="mx-auto w-full max-w-3xl px-4 py-6 pb-28"><header className="flex items-start justify-between gap-4"><div><Link href="/learning" className="text-sm text-muted-foreground">← 学习中心</Link><h1 className="mt-2 text-3xl font-semibold">知识笔记</h1><p className="mt-2 text-sm text-muted-foreground">把过程中的收获沉淀成长期知识。</p></div><Link href="/learning/notes/new" className="shrink-0 rounded-2xl bg-primary px-4 py-3 text-sm font-semibold text-white">＋ 新建</Link></header><LearningNav/><form className="mt-5 grid grid-cols-2 gap-2"><input name="q" defaultValue={filters.q} placeholder="搜索标题、正文或标签" className="min-h-12 rounded-2xl border border-border px-3"/><select name="skillId" defaultValue={filters.skillId ?? ""} className="rounded-2xl border border-border px-3"><option value="">全部技能</option>{skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select><label className="flex min-h-11 items-center gap-2 rounded-2xl bg-surface-muted px-3 text-sm"><input type="checkbox" name="favorite" value="1" defaultChecked={filters.favorite === "1"}/> 只看收藏</label><button className="rounded-2xl bg-surface-muted text-sm font-medium">筛选</button></form><section className="mt-5 space-y-3">{notes.length ? notes.map((note) => <article key={note.id} className="rounded-3xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{skillNames.get(note.skill_id) ?? "关联技能"}</p><h2 className="mt-1 font-semibold">{note.title}</h2></div><span className="text-xl text-amber-500">{note.is_favorite ? "★" : "☆"}</span></div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{note.body}</p>{note.tags.length ? <p className="mt-3 text-xs text-muted-foreground">{note.tags.map((tag) => `#${tag}`).join("  ")}</p> : null}<div className="mt-4 flex gap-3 text-sm"><Link href={`/learning/notes/${note.id}/edit`} className="text-primary">编辑</Link><form action={favoriteNoteAction.bind(null, note.id, note.is_favorite)}><button className="text-primary">{note.is_favorite ? "取消收藏" : "收藏"}</button></form><form action={deleteNoteAction.bind(null, note.id)}><button className="text-red-500">删除</button></form></div></article>) : <div className="rounded-3xl bg-surface-muted p-8 text-center text-sm text-muted-foreground">还没有知识笔记。</div>}</section></main>;
}
